-- Composição do condomínio: áreas por pavimento (QI/QCOMP) e espaços comuns (QVIII).

create table if not exists projetse.condominio_pavimentos (
  id bigint generated by default as identity primary key,
  empreendimento_id bigint not null references projetse.empreendimentos (id) on delete cascade,
  torre text,
  nome text not null,
  area_real numeric,
  area_equivalente numeric,
  ordem integer not null default 0,
  fonte_quadro text check (fonte_quadro in ('qi', 'qcomp'))
);

create index if not exists condominio_pavimentos_empreendimento_id_idx
  on projetse.condominio_pavimentos (empreendimento_id);

create table if not exists projetse.condominio_espacos_comuns (
  id bigint generated by default as identity primary key,
  empreendimento_id bigint not null references projetse.empreendimentos (id) on delete cascade,
  nome text not null,
  ordem integer not null default 0,
  fonte_quadro text check (fonte_quadro in ('qviii'))
);

create index if not exists condominio_espacos_comuns_empreendimento_id_idx
  on projetse.condominio_espacos_comuns (empreendimento_id);

alter table projetse.condominio_pavimentos enable row level security;
alter table projetse.condominio_espacos_comuns enable row level security;

drop policy if exists condominio_pavimentos_select on projetse.condominio_pavimentos;
drop policy if exists condominio_pavimentos_write on projetse.condominio_pavimentos;
drop policy if exists condominio_espacos_comuns_select on projetse.condominio_espacos_comuns;
drop policy if exists condominio_espacos_comuns_write on projetse.condominio_espacos_comuns;

create policy condominio_pavimentos_select
  on projetse.condominio_pavimentos for select to authenticated
  using (projetse.can_access_empreendimento(empreendimento_id));

create policy condominio_pavimentos_write
  on projetse.condominio_pavimentos for all to authenticated
  using (projetse.can_edit_technical(projetse.empreendimento_org_id(empreendimento_id)))
  with check (projetse.can_edit_technical(projetse.empreendimento_org_id(empreendimento_id)));

create policy condominio_espacos_comuns_select
  on projetse.condominio_espacos_comuns for select to authenticated
  using (projetse.can_access_empreendimento(empreendimento_id));

create policy condominio_espacos_comuns_write
  on projetse.condominio_espacos_comuns for all to authenticated
  using (projetse.can_edit_technical(projetse.empreendimento_org_id(empreendimento_id)))
  with check (projetse.can_edit_technical(projetse.empreendimento_org_id(empreendimento_id)));
