-- EPIC-02: tabelas core do Memorial Projetse.

-- ---------------------------------------------------------------------------
-- Funções auxiliares
-- ---------------------------------------------------------------------------

create or replace function projetse.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function projetse.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = projetse, public
as $$
begin
  insert into projetse.profiles (user_id, full_name, email)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', split_part(new.email, '@', 1)),
    coalesce(new.email, '')
  )
  on conflict (user_id) do nothing;

  return new;
end;
$$;

-- ---------------------------------------------------------------------------
-- Organização e acesso
-- ---------------------------------------------------------------------------

create table if not exists projetse.organizations (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists projetse.profiles (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references auth.users (id) on delete cascade,
  full_name text not null,
  email text not null,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists projetse.organization_members (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references projetse.organizations (id) on delete cascade,
  profile_id bigint not null references projetse.profiles (id) on delete cascade,
  role text not null check (role in ('admin', 'gestora', 'responsavel_tecnica', 'revisora')),
  status text not null default 'active' check (status in ('active', 'invited', 'disabled')),
  created_at timestamptz not null default now(),
  unique (organization_id, profile_id)
);

-- ---------------------------------------------------------------------------
-- Incorporadora e empreendimento
-- ---------------------------------------------------------------------------

create table if not exists projetse.incorporadoras (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references projetse.organizations (id) on delete cascade,
  razao_social text not null,
  cnpj text,
  endereco jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists projetse.representantes_legais (
  id bigint generated by default as identity primary key,
  incorporadora_id bigint not null references projetse.incorporadoras (id) on delete cascade,
  nome text not null,
  cpf text,
  rg text,
  estado_civil text,
  regime_comunhao text,
  endereco jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists projetse.empreendimentos (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references projetse.organizations (id) on delete cascade,
  nome text not null,
  incorporadora_id bigint references projetse.incorporadoras (id) on delete set null,
  cidade text,
  uf text,
  endereco text,
  lote text,
  quadra text,
  matricula text,
  responsavel_profile_id bigint references projetse.profiles (id) on delete set null,
  status text not null default 'rascunho',
  progresso integer not null default 0 check (progresso between 0 and 100),
  pendencias_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists projetse.imoveis (
  id bigint generated by default as identity primary key,
  empreendimento_id bigint not null unique references projetse.empreendimentos (id) on delete cascade,
  lote_numero text,
  lote_extenso text,
  quadra_numero text,
  quadra_extenso text,
  loteamento text,
  cidade text,
  comarca text,
  uf text,
  estado_extenso text,
  area_numero numeric,
  area_extenso text,
  benfeitorias text,
  matricula_numero text,
  matricula_extenso text,
  cartorio text
);

create table if not exists projetse.imovel_confrontacoes (
  id bigint generated by default as identity primary key,
  imovel_id bigint not null references projetse.imoveis (id) on delete cascade,
  direcao text not null,
  confrontante text,
  medida text,
  azimute text,
  ordem integer not null default 0
);

create table if not exists projetse.dados_tecnicos (
  id bigint generated by default as identity primary key,
  empreendimento_id bigint not null unique references projetse.empreendimentos (id) on delete cascade,
  area_terreno numeric,
  area_global numeric,
  area_privativa_total numeric,
  area_comum_total numeric,
  torres integer,
  pavimentos integer,
  unidades integer,
  vagas integer,
  alvara text,
  data_aprovacao date,
  responsavel_tecnico text,
  crea_cau text,
  art_rrt text
);

-- ---------------------------------------------------------------------------
-- Quadros, extração e unidades
-- ---------------------------------------------------------------------------

create table if not exists projetse.quadros_tecnicos (
  id bigint generated by default as identity primary key,
  empreendimento_id bigint not null references projetse.empreendimentos (id) on delete cascade,
  storage_path text not null,
  file_name text not null,
  mime_type text,
  size_bytes bigint,
  status text not null default 'enviado' check (status in ('enviado', 'processando', 'processado', 'erro')),
  uploaded_by_profile_id bigint references projetse.profiles (id) on delete set null,
  created_at timestamptz not null default now(),
  processed_at timestamptz
);

create table if not exists projetse.dados_extraidos (
  id bigint generated by default as identity primary key,
  empreendimento_id bigint not null references projetse.empreendimentos (id) on delete cascade,
  quadro_tecnico_id bigint references projetse.quadros_tecnicos (id) on delete set null,
  bloco text not null,
  campo text not null,
  valor text,
  valor_normalizado jsonb,
  confianca numeric,
  status text not null default 'extraido' check (
    status in ('extraido', 'confirmado', 'editado', 'baixa_confianca', 'pendente')
  ),
  reviewed_by_profile_id bigint references projetse.profiles (id) on delete set null,
  reviewed_at timestamptz
);

create table if not exists projetse.unidades_autonomas (
  id bigint generated by default as identity primary key,
  empreendimento_id bigint not null references projetse.empreendimentos (id) on delete cascade,
  nome text not null,
  torre text,
  pavimento text,
  tipo text,
  posicao text,
  area_privativa numeric,
  area_comum numeric,
  area_total numeric,
  area_garden numeric,
  area_garagem numeric,
  fracao text,
  vaga text,
  confrontacoes text,
  observacoes text,
  status text not null default 'nao_revisado' check (
    status in ('validado', 'pendente', 'inconsistencia', 'nao_revisado')
  ),
  updated_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Documentos e memorial
-- ---------------------------------------------------------------------------

create table if not exists projetse.modelos_documento (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references projetse.organizations (id) on delete cascade,
  nome text not null,
  tipo text,
  status text not null default 'ativo',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists projetse.clausulas (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references projetse.organizations (id) on delete cascade,
  modelo_id bigint references projetse.modelos_documento (id) on delete set null,
  titulo text not null,
  categoria text,
  resumo text,
  template text not null,
  variaveis text[],
  status text not null default 'publicada',
  ordem integer not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists projetse.memoriais (
  id bigint generated by default as identity primary key,
  empreendimento_id bigint not null references projetse.empreendimentos (id) on delete cascade,
  versao integer not null default 1,
  status text not null default 'rascunho' check (
    status in ('rascunho', 'gerado', 'em_revisao', 'aprovado', 'exportado')
  ),
  created_by_profile_id bigint references projetse.profiles (id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists projetse.memorial_secoes (
  id bigint generated by default as identity primary key,
  memorial_id bigint not null references projetse.memoriais (id) on delete cascade,
  clausula_id bigint references projetse.clausulas (id) on delete set null,
  titulo text not null,
  conteudo text,
  status text not null default 'nao_gerada' check (
    status in ('nao_gerada', 'gerada', 'em_revisao', 'com_pendencia', 'aprovada')
  ),
  ordem integer not null default 0,
  approved_by_profile_id bigint references projetse.profiles (id) on delete set null,
  approved_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists projetse.document_exports (
  id bigint generated by default as identity primary key,
  memorial_id bigint not null references projetse.memoriais (id) on delete cascade,
  empreendimento_id bigint not null references projetse.empreendimentos (id) on delete cascade,
  tipo text not null check (tipo in ('revisao', 'final')),
  formato text not null check (formato in ('docx', 'pdf')),
  storage_path text,
  status text not null default 'pendente',
  created_by_profile_id bigint references projetse.profiles (id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists projetse.pendencias (
  id bigint generated by default as identity primary key,
  empreendimento_id bigint not null references projetse.empreendimentos (id) on delete cascade,
  entidade_tipo text,
  entidade_id bigint,
  severidade text not null default 'atencao' check (severidade in ('info', 'atencao', 'bloqueante')),
  mensagem text not null,
  status text not null default 'aberta' check (status in ('aberta', 'resolvida', 'ignorada')),
  created_by_profile_id bigint references projetse.profiles (id) on delete set null,
  resolved_by_profile_id bigint references projetse.profiles (id) on delete set null,
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);

create table if not exists projetse.audit_events (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references projetse.organizations (id) on delete cascade,
  empreendimento_id bigint references projetse.empreendimentos (id) on delete set null,
  profile_id bigint references projetse.profiles (id) on delete set null,
  event_type text not null,
  description text not null,
  metadata jsonb,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Índices
-- ---------------------------------------------------------------------------

create index if not exists idx_organization_members_org on projetse.organization_members (organization_id);
create index if not exists idx_organization_members_profile on projetse.organization_members (profile_id);
create index if not exists idx_empreendimentos_org on projetse.empreendimentos (organization_id);
create index if not exists idx_incorporadoras_org on projetse.incorporadoras (organization_id);
create index if not exists idx_unidades_empreendimento on projetse.unidades_autonomas (empreendimento_id);
create index if not exists idx_audit_events_org on projetse.audit_events (organization_id, created_at desc);
create index if not exists idx_audit_events_empreendimento on projetse.audit_events (empreendimento_id, created_at desc);

-- ---------------------------------------------------------------------------
-- Triggers updated_at
-- ---------------------------------------------------------------------------

create trigger organizations_set_updated_at
  before update on projetse.organizations
  for each row execute function projetse.set_updated_at();

create trigger profiles_set_updated_at
  before update on projetse.profiles
  for each row execute function projetse.set_updated_at();

create trigger incorporadoras_set_updated_at
  before update on projetse.incorporadoras
  for each row execute function projetse.set_updated_at();

create trigger representantes_legais_set_updated_at
  before update on projetse.representantes_legais
  for each row execute function projetse.set_updated_at();

create trigger empreendimentos_set_updated_at
  before update on projetse.empreendimentos
  for each row execute function projetse.set_updated_at();

create trigger unidades_autonomas_set_updated_at
  before update on projetse.unidades_autonomas
  for each row execute function projetse.set_updated_at();

create trigger modelos_documento_set_updated_at
  before update on projetse.modelos_documento
  for each row execute function projetse.set_updated_at();

create trigger clausulas_set_updated_at
  before update on projetse.clausulas
  for each row execute function projetse.set_updated_at();

create trigger memorial_secoes_set_updated_at
  before update on projetse.memorial_secoes
  for each row execute function projetse.set_updated_at();

-- Trigger de perfil ao criar usuário auth (nome específico — não sobrescreve outros apps)
drop trigger if exists projetse_on_auth_user_created on auth.users;

create trigger projetse_on_auth_user_created
  after insert on auth.users
  for each row execute function projetse.handle_new_user();

-- ---------------------------------------------------------------------------
-- Grants de tabela (RLS restringe o acesso efetivo)
-- ---------------------------------------------------------------------------

grant select, insert, update, delete on all tables in schema projetse to authenticated;
grant select on all tables in schema projetse to anon;
grant usage, select on all sequences in schema projetse to authenticated;

alter default privileges in schema projetse
  grant select, insert, update, delete on tables to authenticated;

alter default privileges in schema projetse
  grant select on tables to anon;
