/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppModelosRouteImport } from './routes/_app.modelos'
import { Route as AppHistoricoRouteImport } from './routes/_app.historico'
import { Route as AppConfiguracoesRouteImport } from './routes/_app.configuracoes'
import { Route as AppClausulasRouteImport } from './routes/_app.clausulas'
import { Route as AppEmpreendimentosIndexRouteImport } from './routes/_app.empreendimentos.index'
import { Route as AppEmpreendimentosNovoRouteImport } from './routes/_app.empreendimentos.novo'
import { Route as AppEmpreendimentosIdRouteImport } from './routes/_app.empreendimentos.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppModelosRoute = AppModelosRouteImport.update({
  id: '/modelos',
  path: '/modelos',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoricoRoute = AppHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppClausulasRoute = AppClausulasRouteImport.update({
  id: '/clausulas',
  path: '/clausulas',
  getParentRoute: () => AppRoute,
} as any)
const AppEmpreendimentosIndexRoute = AppEmpreendimentosIndexRouteImport.update({
  id: '/empreendimentos/',
  path: '/empreendimentos/',
  getParentRoute: () => AppRoute,
} as any)
const AppEmpreendimentosNovoRoute = AppEmpreendimentosNovoRouteImport.update({
  id: '/empreendimentos/novo',
  path: '/empreendimentos/novo',
  getParentRoute: () => AppRoute,
} as any)
const AppEmpreendimentosIdRoute = AppEmpreendimentosIdRouteImport.update({
  id: '/empreendimentos/$id',
  path: '/empreendimentos/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/clausulas': typeof AppClausulasRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/historico': typeof AppHistoricoRoute
  '/modelos': typeof AppModelosRoute
  '/empreendimentos/$id': typeof AppEmpreendimentosIdRoute
  '/empreendimentos/novo': typeof AppEmpreendimentosNovoRoute
  '/empreendimentos/': typeof AppEmpreendimentosIndexRoute
}
export interface FileRoutesByTo {
  '/clausulas': typeof AppClausulasRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/historico': typeof AppHistoricoRoute
  '/modelos': typeof AppModelosRoute
  '/': typeof AppIndexRoute
  '/empreendimentos/$id': typeof AppEmpreendimentosIdRoute
  '/empreendimentos/novo': typeof AppEmpreendimentosNovoRoute
  '/empreendimentos': typeof AppEmpreendimentosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/clausulas': typeof AppClausulasRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/historico': typeof AppHistoricoRoute
  '/_app/modelos': typeof AppModelosRoute
  '/_app/': typeof AppIndexRoute
  '/_app/empreendimentos/$id': typeof AppEmpreendimentosIdRoute
  '/_app/empreendimentos/novo': typeof AppEmpreendimentosNovoRoute
  '/_app/empreendimentos/': typeof AppEmpreendimentosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clausulas'
    | '/configuracoes'
    | '/historico'
    | '/modelos'
    | '/empreendimentos/$id'
    | '/empreendimentos/novo'
    | '/empreendimentos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/clausulas'
    | '/configuracoes'
    | '/historico'
    | '/modelos'
    | '/'
    | '/empreendimentos/$id'
    | '/empreendimentos/novo'
    | '/empreendimentos'
  id:
    | '__root__'
    | '/_app'
    | '/_app/clausulas'
    | '/_app/configuracoes'
    | '/_app/historico'
    | '/_app/modelos'
    | '/_app/'
    | '/_app/empreendimentos/$id'
    | '/_app/empreendimentos/novo'
    | '/_app/empreendimentos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/modelos': {
      id: '/_app/modelos'
      path: '/modelos'
      fullPath: '/modelos'
      preLoaderRoute: typeof AppModelosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/historico': {
      id: '/_app/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AppHistoricoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clausulas': {
      id: '/_app/clausulas'
      path: '/clausulas'
      fullPath: '/clausulas'
      preLoaderRoute: typeof AppClausulasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/empreendimentos/': {
      id: '/_app/empreendimentos/'
      path: '/empreendimentos'
      fullPath: '/empreendimentos/'
      preLoaderRoute: typeof AppEmpreendimentosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/empreendimentos/novo': {
      id: '/_app/empreendimentos/novo'
      path: '/empreendimentos/novo'
      fullPath: '/empreendimentos/novo'
      preLoaderRoute: typeof AppEmpreendimentosNovoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/empreendimentos/$id': {
      id: '/_app/empreendimentos/$id'
      path: '/empreendimentos/$id'
      fullPath: '/empreendimentos/$id'
      preLoaderRoute: typeof AppEmpreendimentosIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppClausulasRoute: typeof AppClausulasRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppHistoricoRoute: typeof AppHistoricoRoute
  AppModelosRoute: typeof AppModelosRoute
  AppIndexRoute: typeof AppIndexRoute
  AppEmpreendimentosIdRoute: typeof AppEmpreendimentosIdRoute
  AppEmpreendimentosNovoRoute: typeof AppEmpreendimentosNovoRoute
  AppEmpreendimentosIndexRoute: typeof AppEmpreendimentosIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppClausulasRoute: AppClausulasRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppHistoricoRoute: AppHistoricoRoute,
  AppModelosRoute: AppModelosRoute,
  AppIndexRoute: AppIndexRoute,
  AppEmpreendimentosIdRoute: AppEmpreendimentosIdRoute,
  AppEmpreendimentosNovoRoute: AppEmpreendimentosNovoRoute,
  AppEmpreendimentosIndexRoute: AppEmpreendimentosIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
